project_id = "dmtnwfdjcapiketfcrur"

[functions.linkedin-api]
verify_jwt = false

[functions.linkedin-auth]
verify_jwt = false

[functions.generate-post]
verify_jwt = false

[functions.generate-image]
verify_jwt = false
